# plotter.py
import numpy as np
import matplotlib.pyplot as plt

# Update file_name to match the CSV file generated by main.py in the ../data folder.
file_name = "data_2025-04-17_09-47-35.csv"  # Replace with your actual file name

# Load simulation data.
# Each row: [time, state (13 values), motor forces (4 values)]
data = np.loadtxt("C:/Users/Sanat/Documents/" + file_name, delimiter=",")
print("Data shape:", data.shape)  # For debugging, prints the shape of the data matrix

# Compute altitude vs. time.
# Altitude (z) is stored as the third element of the state vector.
# Since time is the first element, and state occupies columns 1 to 13, altitude is at column index 3.
time = data[:, 0]
altitude = data[:, 3]

# Compute total thrust vs. time.
# The motor forces are stored in the last 4 columns (indices 14,15,16,17).
total_thrust = data[:, 14] + data[:, 15] + data[:, 16] + data[:, 17]

# Create a figure for altitude.
plt.figure(1)
plt.plot(time, altitude, label="Altitude")
plt.xlabel("Time (s)")
plt.ylabel("Altitude (m)")
plt.title("Drone Altitude vs. Time")
plt.grid()
plt.legend()

# Create a figure for total thrust.
plt.figure(2)
plt.plot(time, total_thrust, label="Total Thrust", color="orange")
plt.xlabel("Time (s)")
plt.ylabel("Total Thrust (N)")
plt.title("Total Motor Thrust vs. Time")
plt.grid()
plt.legend()

plt.show()
